[package]
name = "mqtt-client"
version = "0.1.0"
authors = ["Qian Linfeng <thewawar@gmail.com>"]

[dependencies]
clap = "^1.4.0"
log = "^0.3.2"
env_logger = "^0.3.1"
uuid = "^0.1.17"
time = "0.1"

[dependencies.mqtt-protocol]
path = "../"

[[bin]]
name = "mqttc"
